# .pre-commit-config.yaml
# See https://pre-commit.com/ for usage and config
repos:
  - repo: local
    hooks:
      - id: update-index
        name: Update README index
        language: script
        pass_filenames: false
        entry: .make-index
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ["--maxkb=600"]
